apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: jenkins-deployer
      containers:
        - name: flask-app
          image: DOCKER_USER/flask-cicd:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['app/version']
