apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: demo
spec:
  selector:
    app: flask-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30550
